epochs: 200
output_dir: output_dir

model:
  name: DualBoost
  backbone:
    name: ResNetCifar
    depth: 50
  neck:
    name: NonLinearNeckV2
    in_channels: 2048
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: True
  predictor:
    name: Predictor
    in_channels: 256
    hid_channels: 256
    out_channels: 256
  head:
    name: L2Head

dataloader:
  train:
    num_workers: 8
    sampler:
      batch_size: 512
      shuffle: true
      drop_last: true
    dataset:
      name: CIFAR100
      mode: 'train'
      return_label: False
      return_two_sample: True
      download: True
      transforms:
        - name: RandomResizedCrop
          size: 32
          scale: [0.2, 1.]
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 0.5
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]

lr_scheduler:
  name: CosineAnnealingDecay
  learning_rate: 3.2
  T_max: 200


optimizer:
  name: Momentum
  weight_decay: 5e-4

log_config:
    name: LogHook
    interval: 1
