epochs: 300
output_dir: output_dir

model:
  name: BYOL
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: NonLinearNeckV2
    in_channels: 2048
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: True
  predictor:
    name: NonLinearNeckV2
    in_channels: 256
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: False
  head:
    name: L2Head
  target_decay_method: cosine # cosine
  target_decay_rate: 0.996
  align_init_network: True
  use_synch_bn: True

dataloader:
  train:
    num_workers: 4
    sampler:
      batch_size: 64
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: False
      return_two_sample: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.08, 1.]
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 0.5
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineAnnealingDecay
    learning_rate: 0.1
    T_max: 300
  warmup_steps: 10
  start_lr: 0.0001
  end_lr: 0.2


optimizer:
  name: Momentum
  weight_decay: 1.5e-6

log_config:
    name: LogHook
    interval: 1

custom_config:
  - name: BYOLHook
